name: CI

on:
  push:
  pull_request: 
  workflow_dispatch:

jobs:
  test:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.8
      with:
        key: docker-cache-${{ hashFiles('**/package-lock.json') }}-{hash}
        restore-keys: |
          docker-cache-${{ hashFiles('**/package-lock.json') }}

    - run: docker-compose build client_dev
    - run: docker-compose run client_dev npm test

    - uses: codecov/codecov-action@v1
      if: github.event_name == 'push'
      timeout-minutes: 1
      continue-on-error: true
      with:
        directory: ./client/coverage/

  build:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.8
      with:
        key: docker-cache-${{ hashFiles('**/package-lock.json') }}-{hash}
        restore-keys: |
          docker-cache-${{ hashFiles('**/package-lock.json') }}

    - run: docker-compose build client_dev
    - run: docker-compose run client_dev npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.8
      with:
        key: docker-cache-${{ hashFiles('**/package-lock.json') }}-{hash}
        restore-keys: |
          docker-cache-${{ hashFiles('**/package-lock.json') }}

    - run: docker-compose build client_dev

    - run: docker-compose run client_dev npm run lint
      if: github.event_name != 'workflow_dispatch'

    - run: docker-compose run client_dev npm run lint --fix
      if: github.event_name == 'workflow_dispatch'

    - name: Commit & push
      if: github.event_name == 'workflow_dispatch'
      run: |
        git add .
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git commit -m "lint fix"
        git push
